spring.application.name=uberApp
#spring.debug=true
#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate=DEBUG

spring.port=8090
# DB Config
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?useSSL=false
#spring.datasource.role=aniketk
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true